# Generated by Django 3.2 on 2021-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('bust', models.FloatField()),
                ('waist', models.FloatField()),
                ('hips', models.FloatField()),
                ('top_size', models.FloatField()),
                ('jeans_size', models.FloatField()),
            ],
        ),
    ]
