# Generated by Django 3.2 on 2021-05-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurements',
            new_name='Measurement',
        ),
    ]
