# Generated by Django 3.2 on 2021-05-06 13:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('TheAPI', '0002_rename_measurements_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='bust',
            new_name='Bust',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='firstname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='hips',
            new_name='Hips',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='lastname',
            new_name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='waist',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='jeans_size',
            new_name='Waist',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='top_size',
        ),
        
        migrations.AddField(
            model_name='measurement',
            name='Across_Back',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Across_Front',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Contact_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+233XXXXXXXXX', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Dress_Length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Long_Sleeve',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Lower_Waist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Short_Sleeve',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Shoulder_to_Hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Shoulder_to_Waist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Skirt_Length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
